#!/usr/bin/make -f

CC=gcc

TEST_SOURCES=crypt_test.c ../md5.c enc_type_1.c enc_type_2.c enc_type_20.c
TEST_OBJS=crypt_test.o ../md5.o enc_type_1.o enc_type_2.o enc_type_20.o
CFLAGS=-O2 -Wall -I../ -g
LDFLAGS=-lm

all: $(TEST_OBJS)
	$(CC) -o crypt_test $(CFLAGS) $(LDFLAGS) $(TEST_OBJS)
	@./crypt_test all	

#tests: test_1 test_2 test_20

#test_%: enc_type_%.c ${TEST_SOURCES}
#	@echo -n $<...
#	@gcc ${CFLAGS} ${LDFLAGS} -o $@ ${TEST_SOURCES} $< -DCRYPT_FUNC=${<:.c=}
#	@./$@ |md5sum |cmp - test_$*.md5 && echo -e ' \tpass' || echo -e ' \tFAIL'
